### ISSUE TITLE
Anaconda wont start

### ISSUE THREAD

**Issue by antoniopicone** [mikeeq/mbp-fedora#10]
Hi,
I have a 2019 MBP 13inch disabled secure boot and rebooted into your Fedora: just wifi doesn-t work ootb but Anaconda won-t start.
Please find anaconda.log attached.

[anaconda.log](https://github.com/mikeeq/mbp-fedora/files/4044415/anaconda.log)

I really appreciate your effort to make Linux work on Mac.

Thank you.

**Comment by mikeeq** [comment]
Should be fixed in v5.4.10-f31 release ;)

**Comment by antoniopicone** [comment]
it works! thank you! 🤟🏻
