### ISSUE TITLE
Other languages during setup

### ISSUE THREAD

**Issue by antoniopicone** [mikeeq/mbp-fedora#11]
Hi,
could you please add other languages during setup ? I'd like to set Italian language :)

Thank you very much.

**Comment by antoniopicone** [comment]
(I've read your readme and I'll add manually, later...but it would be nice to have at setup: does it make image way bigger ?)

**Comment by mikeeq** [comment]
Yes it does, much bigger. It will slow down whole building process, so as for know if all issues are not sorted I will leave it with english only. Later on if image will be stable, i will add additional languages ;)

**Comment by antoniopicone** [comment]
ok, thank you.
