### ISSUE TITLE
MacBook Pro 15,4 WiFi driver setup

### ISSUE THREAD

**Issue by antoniopicone** [mikeeq/mbp-fedora#12]
Hi,
running `ioreg -l | grep RequestedFiles` on my MBP 2019, gives: 

`"RequestedFiles" = ({"Firmware"="C-4377__s-B3/formosa.trx","TxCap"="C-4377__s-B3/formosa-X3.txcb","Regulatory"="C-4377__s-B3/formosa-X3.clmb","NVRAM"="C-4377__s-B3/P-formosa-X3_M-SPPR_V-m__m-3.1.txt"})`

So I copied the three files from MacOS and renamed into:

`brcmfmac4377-pcie.bin`
`brcmfmac4377-pcie.Apple Inc.-MacBookPro15,4.txt`
`brcmfmac4377-pcie.clm_blob`

In Fedora, I copied them into /lib/firmware/brcm but no wifi hw is detected.

Am I doing something wrong ?

thankyou!

**Comment by ktb92677** [comment]
You should probably take a look at this thread: https://github.com/mikeeq/mbp-fedora-kernel/issues/3

**Comment by mikeeq** [comment]
Antonio please... :D yeah, we have some issues with BCM4377 check other threads ;)
