### ISSUE TITLE
Latest release doesn't boot on MBA8,2

### ISSUE THREAD

**Issue by ktb92677** [mikeeq/mbp-fedora#13]
Hi @mikeeq, I just downloaded the latest release of mbp-fedora (v5.4.10-f31). The live boot process seems to stay frozen at the screen with the spinning wheel and fedora text + Logo. Anything I should try to debug?

EDIT: I can indeed confirm that release v5.3.15-2-f31 does indeed still boot on my MBA8,2. Don't know if that information helps in the debugging process.

**Comment by mikeeq** [comment]
Try clicking any key whenever you are on `spinning wheel screen`, you should be able to see logs.

**Comment by mikeeq** [comment]
@ktb92677 try redownloading the image and reburning it to your usb storage device (or try different one) it's booting correctly for me - MBP 15,2

**Comment by ktb92677** [comment]
Okay for some reason after many attempts to boot from the ISO it finally just started booting. Hitting the return key a bunch will for some reason make the ISO boot. Issue closed.

**Comment by ktb92677** [comment]
No there's still something wrong. The laptop goes in very odd boot cycles after rebooting the system. My Mac will not boot unless I repeatedly hit the return key on on the keyboard. Why is this?

**Comment by mikeeq** [comment]
@ktb92677 Could you please give an update on this issue? Are you still experiencing any issues with 5.5.x releases?

**Comment by ktb92677** [comment]
Yes! This seems to be fixed in the latest release. I am closing out this issue
