### ISSUE TITLE
Failed to start Switch Boot.

### ISSUE THREAD

**Issue by loafbox** [mikeeq/mbp-fedora#2]
LiveCD is working great.  The install also completed, however when I try to boot I get an error that "Failed to switch root on boot"?  And the process hangs.  Any idea what's happening here?

**Comment by mikeeq** [comment]
You need to provide me some more details ;) Maybe record a video of actual boot process, i don't know if it's hanging on trying to load grub or after. Which MacBook are you actually using and how your partition table looks like ;)

**Comment by loafbox** [comment]
Here's photo of boot sequence:
https://drive.google.com/file/d/13qwkgyMstTdLZC3P9s6E4vds_-VWt0C2/view?usp=sharing

Kernel:
https://drive.google.com/file/d/13p83b_hzZgjyfMPHXzORXeAJOhLU1PUH/view?usp=sharing


This is a 2019 15" Macbook Pro.  I tried both auto partition and custom.  With custom, I used all the suggested partitions, except change fs type to ext4.

**Comment by mikeeq** [comment]
Do you have separate partitions for `/boot/efi` HFS+ ESP and for `/boot`?

I'm using this standard partition layout (not LVM):
- /boot/efi - 1024MB Linux HFS+ ESP
- /boot - 1024MB EXT4
- / - 120GB EXT4

Remember that you don't need to use rEFInd, you should be able to boot directly from MacOS boot manager. (you can boot into it by pressing and holding option key after clicking power-on button)

**Comment by loafbox** [comment]
Thanks, sounds like I need to do some experimenting.  I do have rEFInd installed.  Might go nuclear and start over.  If turns out issue isn't on my end, will re-open.

**Comment by mikeeq** [comment]
@loafbox You also should boot Fedora Installer USB via MacOS boot manager. There will be three boot options available, usually the third one works for me. (There are three of them, because there are three partitions in ISO: 1) ISO9660 - with installer data, 2) fat32, 3) hfs+)

**Comment by loafbox** [comment]
Alright got it working now, and I *think* it's because I had LVM on the root and it should have been standard.?.  But all I did was delete the partitions from previous install, and re-install with the exact layout from your comment and everything is good - thanks!

**Comment by mikeeq** [comment]
I haven't tested any other layouts than standard, my bad. I will try to remember about it during the next release. I'm glad that it's working for you. Cheers Mate.
