### ISSUE TITLE
Can't boot into installed system on Macbook15,2

### ISSUE THREAD

**Issue by folke** [mikeeq/mbp-fedora#20]
Initially Anaconda wouldn't load, but I was able to fix that by adding `modprobe.blacklikst=thunderbolt` to the boot parameters.

After this, I successfully was able to install Fedora.

After rebooting with the option key, I have a new boot entry `EFI Boot` (which I assume is the one for Fedora?), but when I pick that, it eventually starts the recovery manager saying that additional software is required to boot from that partition.

Am I missing something obvious here? Is there another way I need to boot to get into the installed system?

Thanks in advance!

**Comment by mikeeq** [comment]
Are you following the tutorial from readme.md? How did you put the ISO on your USB stick - all grub kernel args should be already in place, you shouldn't need to edit manually anything ;) (in theory)

Are you using the latest release?

**Comment by folke** [comment]
Hi! Im using the latest release. Without the extra blacklist parameter, the installer doesn't boot.

I used the fedora disk utility in macos.

I was initially confused with the "standard" layout. I thought it referred to the default partitions, but in the meantime I found you need to chose "custom" and then standard as partitioning scheme (and not LVM).

Did it that way this morning, but didn't work either.

Trying again right now, just in case I missed something. Will report back

**Comment by folke** [comment]
I do have the extra swap partition. Would that cause any issues?

**Comment by folke** [comment]
Same issue again after retrying. When I choose Efi Boot after installation, it starts the macos recovery tool with the error message:

A software update is required to use this startup disk

**Comment by folke** [comment]
This is odd. I copied the image using Rufus in parallels instead now and the grub parameters are completely different. 

Froze initially, but running the installer right now with basic graphics.

Fingers crossed 🤞

**Comment by folke** [comment]
Now it works! Not sure what happened, but apparently the Fedora Media Writer messed something up

**Comment by mikeeq** [comment]
Glad to hear that. Cheers @folke .
