### ISSUE TITLE
Is it safe to remove nomodeset for a 13 inch macbook pro, Macbook15,2?

### ISSUE THREAD

**Issue by folke** [mikeeq/mbp-fedora#21]
First of all, a big thanks for working on this project!

I noticed nomodeset is part of the grub command line. After removing it, the GPU is enabled and everything seems to be working perfectly fine on my macbook pro 13 inch. Everything obviously runs way smoother as a result and the screen brightness can be adjusted.

Is there any reason I would not want to remove nomodeset?

**Comment by mikeeq** [comment]
`nomodeset` is not a part of my cmdline kernel args - awkward :D Have you changed anything manually?

```
rhgb quiet efi=noruntime pcie_ports=compat modprobe.blacklist=thunderbolt systemd.unified_cgroup_hierarchy=0 brcmfmac.rambase_addr=0x160000
```

**Comment by folke** [comment]
Maybe it was added during installation since I had to use the installer in basic graphics mode?

**Comment by folke** [comment]
Closing this. Not an issue at all it seems :-)
