### ISSUE TITLE
installing fedora on iMacpro 1,1

### ISSUE THREAD

**Issue by mariakesa** [mikeeq/mbp-fedora#24]

**Comment by mariakesa** [comment]
Hello,

I'm trying to install your mbp-fedora on iMacPro 1,1 and I get the following screen after burning the iso and booting into the disk I get the following screen and it hangs in it
`https://github.com/mariakesa/Neural-Data-Analysis/blob/master/IMG_0671.jpg`
Any help would be appreciated!

**Comment by mikeeq** [comment]
Try to add nomodeset to kernel args ;)
