### ISSUE TITLE
External monitors don't work

### ISSUE THREAD

**Issue by matteha** [mikeeq/mbp-fedora#25]
Thanks for the great work! Been using mbp-fedora on my MBP 2018.

Just a heads up, may be worth mentioning in the README as well: external monitors don't seem to work on mbp-fedora on my laptop (MBP with dgpu AMD). Tried different monitors and different cables but no luck. They work instantly with mbp-ubuntu so it seems to be an mbp-fedora problem.

**Comment by direlime** [comment]
I fixed this problem on my MBP 15,3 2019 with the dGPU by removing the nomodeset kernel argument at boot. This allows the gnome-session to start in Wayland, which supports the external monitors.

Hope this helps.

**Comment by mikeeq** [comment]
Thanks for the info!
