### ISSUE TITLE
Fedora 33 installed in an SSD boots in Macbook pro (2015) but doesn't on Mac mini (2018)

### ISSUE THREAD

**Issue by Zodeck** [mikeeq/mbp-fedora#30]
MacBook Pro has only 10.14.6 installed
Mac mini has 11.1, 10.14.6 and windows (bootcamp)

Fedora 33 is installed in an external NVMe M.2 solid state drive;

**Comment by Vestaia** [comment]
What is the error? Boot with `loglevel=7` kernel parameter to get debug messages. 
What are you using to boot (Apple EFI bootloader, rEFInd, Grub)? 
Neither the MacBook or the Mac Mini has an external M.2 port. What are you using? USB, Thunderbolt?
Have you generated the initramfs using `dracut` with the needed modules for both devices?

**Comment by mikeeq** [comment]
@Zodeck please add some more details
