### ISSUE TITLE
Macbookpro A2141: Live usb won't boot up: Warning: /dev/disk/by-label/fedora-mbp=x86_64-202106231409 does not exist

### ISSUE THREAD

**Issue by skywalkerz0r** [mikeeq/mbp-fedora#36]
Hi,

I am trying to boot the image livecd-fedora-mbp-202106231409.iso on a Macbook pro A2141.

I did the steps described in the README, when I click on the third option (second EFI boot option), it goes to grub.
From there I select the first option, I see the Fedora splash screen. After a minute or so, I have the error below.
The keyboard won't work. Neither the MacBook kb nor a USB one. I am stuck there. Any ideas?

The complete error message is in the image attached.
![error](https://user-images.githubusercontent.com/47341410/126050518-3c5cc386-5974-423b-9a79-7bad120133e9.jpg)

**Comment by skywalkerz0r** [comment]
Oh, by the way, I have this same issue trying to boot up Fedora 33 from the upstream directly.
I found this page here, with a guy saying simply type in "exit", however, like I said the keyboard won't work ;( 

https://cialu.net/fedora-not-boot-on-macbook-pro/

**Comment by mikeeq** [comment]
It seems like wrongly created live usb, have you created live usb using `dd` command?

**Comment by skywalkerz0r** [comment]
Damn, you're right. I used the fedora media creator. 
As I had the same issue I was getting with the fedora upstream, I didn't consider it as the problem. Thanks Mike

**Comment by skywalkerz0r** [comment]
@mikeeq btw, thunderbolt seems to work here!
i modprobed it, and i can use another screen.
i am testing the live image now.

when should i be seeing the kernel panic issue?
