### ISSUE TITLE
Audio profile is not changed/setup correctly when done from Gnome Settings Sound tab

### ISSUE THREAD

**Issue by mikeeq** [mikeeq/mbp-fedora#39]
https://github.com/mikeeq/mbp-fedora-kernel/issues/17

**Comment by mikeeq** [comment]
@sxiii can you verify if it's fixed now?

**Comment by sxiii** [comment]
Unfortunately I can't really verify this as I don't own the macbookpro anymore. I was fortunate enough to convince my company to get me a proper laptop. :)
