### ISSUE TITLE
Cannot boot live USB on Mac Mini (2018)

### ISSUE THREAD

**Issue by eskimooo** [mikeeq/mbp-fedora#4]
Hi, I'm trying to test this on a Mac Mini (2018), but I cannot actually boot into the installer.

1. Booting to Mac Boot Selection works fine, I'm able to select the 3rd option for EFI Boot.
2. I can see and select the options to boot:

- Start Livecd Fedora
- Test this media & start Livecd Fedora
- Troubleshooting -->

3. At this stage, I select the "Start Livecd Fedora" option, and it seems to progress.
4. System appears to boot but gets stuck with the following messages:
```
BCMDHD_ExitBootService: ENTER
dhd_os_wifi_platform_set_power: Setting wl_reg_on to 0 succeeded
dhd_os_wifi_platform_set_power: Setting wl_reg_on to 1 succeeded
```

At this point, there is nothing I can do, it does not progress past this error. 

As this is a Mac Mini, I don't necessarily need the wireless since I have an Ethernet cable plugged in for networking, but it looks like it still wants to try the wireless. 

Any thoughts or other things I can try to get this booting to the installer? 

Cheers!

**Comment by Kvitz** [comment]
@eskimooo Has it ever worked before, or is this your first try? Do you still have macOS installed and if so, which version? Is it up to date? Today I have updated to 10.14.6 and now I can't boot, neither from the live usb nor the actual installation which had been running up until now.

From the selection menu, could you edit the kernel boot command line and remove the `quiet` argument and replace it with verbose? This should show the kernel log and call stack when it crashes.

**Comment by mikeeq** [comment]
I'm working on a new build with F31, 5.3 kernel and disabled thunderbolt driver by default - maybe it will work for you, because most of the boot problems are caused by failures during thunderbolt firmware loading.

BTW I don't know why I don't receive notifications whenever someone create a new issue on github...

**Comment by Kvitz** [comment]
Thanks for the update @mikeeq. After the Security Update 2019-001 and Security Update 2019-006 on mojave the fedora kernel (f30 v5.1.19-7) now panics with a page fault:
`arch/x86/platform/efi/quirks.c:734 efi_recover_from_page_fault+0x2a/0xc0`

If you have any (pre-)release I could test I'd be thankful, as I'm completely unable to boot linux now, even from a live usb. I used to be able to boot a standard ubuntu (although the nvme wouldn't be detected, nor the internal keyboard and trackpad worked, etc) but at least I could boot the kernel all the way to the actual desktop, but even that now fails.

I also tried building an .iso with your latest pre-release kernels, by downloading them and editing the kickstart configuration to not pickup the kernel rpms from the heroku repo and install the downloaded ones, but I think I ended up with a standard fedora kernel instead.

I haven't updated to catalina as I don't know will it make things better or worse.

**Comment by rui-r3** [comment]
I've learnt that the EFI firmware can be updated and I guess one of the security updates did so. This could be the reason why we can't boot linux.

@eskimooo Could you share with us which version of iBridge are you running? You can check it on the `System Information -> Hardware -> Boot ROM version`.

**Comment by rui-r3** [comment]
I've learnt the EFI firmware can be updated, which might have happened with one of the security updates installations.

@eskimooo Could you share with us which version of iBridge are you running? You can check on `System Information -> Hardware -> Boot ROM version".

@mikeeq Are you aware of any way to downgrade the EFI firmware? The Apple Configurator 2 seems to download the latest version.

**Comment by Kvitz** [comment]
I've learnt the EFI firmware can be updated, which might have happened with one of the security updates installations.

@eskimooo Could you share with us which version of iBridge are you running? You can check on `System Information -> Hardware -> Boot ROM version".

@mikeeq Are you aware of any way to downgrade the EFI firmware? The Apple Configurator 2 seems to download the latest version.

**Comment by mikeeq** [comment]
I'm not aware of any way of downgrading EFI firmware on Macs and yes you're right EFI could be upgraded during OS/security update. I don't have any other Macs to test why is it failing on new version of EFI. Are you sure that secure boot is turned off after EFI update? Have you tried to boot windows or any other Linux distro from USB and was any of these successful?

**Comment by Kvitz** [comment]
I have tried a stock ubuntu 18.04, which used to boot all the way up to the installer (but keyboard, touchpad, nvme, etc, didn't work), but now it doens't work, neither do your f30 images from a live usb, which I have used before to install linux on mac and were working very well until the update.
I haven't tried windows but I guess I could try bootcamp and a windows usb installed to see if it would work.

My versions are:
```
  Boot ROM Version:	1037.40.124.0.0 (iBridge: 17.16.11081.0.0,0)
  System Version:	macOS 10.14.6 (18G1012)
```

Given the kernel stack trace I suspect the firmware upgrade has messed things up. It would be interesting to know @eskimooo versions or anyone else with a similar issue.
My recommendation until someone understands what's failing is not to install any updates. I have inspected the contents of the update package and seen an `EFIFirmware.pkg` and others (embeddedOS, etc) as part of the security update I mentioned before, so these updates can be very quietly sneaked in. I didn't find any mention to the firmware update on apple's security update page.

Thanks a lot for your feedback @mikeeq. Your distro was working beautifully until I decided to run the updates on the macOS side.

**Comment by mikeeq** [comment]
F31 is coming ;) should be ready in 30 mins.

**Comment by Kvitz** [comment]
@mikeeq Awesome :D I've given it a spin and unfortunately it doesn't solve my efi issue. I will keep investigating to see if there is some way of forcing an older version to be installed.

Thank you for another release!

**Comment by eskimooo** [comment]
I actually ended up selling the Mac Mini and no longer have it available for testing. Feel free to close the issue if you'd like.

Thanks for the initial assistance though.

**Comment by mikeeq** [comment]
```
aunali1
@mikee u have to pass noapic efi=noruntime nomodeset as kernel args
 
aunali1
the new EFI fw that comes with catalina and the newer security updates seems to have introduced a new efi bootservice that screws with linux.
```
I will try to implement those changes into the Fedora Image this week, so it should fix all your problems. @Kvitz

**Comment by Kvitz** [comment]
@mikeeq Thank you so much! I can boot the fedora 30 I had installed with those kernel args and also the fedora 31 live image you released! I only needed `efi=noruntime` on my macbook 15,1 in order to boot the kernel.

I haven't got catalina installed but I do have the security updates. I believe the current catalina is on the same EFI version though, so these kernel args might work as well.

Thank you very much for the help!

**Comment by leifliddy** [comment]
I need a minipc running Fedora that just needs to connect to a thunderbolt 3 disk enclosure (which will act as my home nas) If someone manages to get Linux running on the Mac Mini 2018 w/ working thunderbolt 3, please let me know. I'm also not opposed to buying a Mac Mini if it would help progress the development of this project. I could perform testing + troubleshooting...etc. Please let me know what your thoughts are on this. What is the probability that the Mac Mini would be fully functional with Linux someday?

**Comment by mikeeq** [comment]
Hi @leifliddy,

At the moment Thunderbolt driver is not compatible with Macs with Apple T2 on board (It's disabled in my Fedora build), from kernel 5.2 it's crashing Mac during boot. I don't know if it was working or not on 5.1, because it was failing when it was trying to load TB firmware and I don't have and TB device to test it. I recommend to build/buy standard PC with TB - AMD CPUs are now really cheap ;)

**Comment by leifliddy** [comment]
I have a mini-itx case, and TB3 on a mini-itx MB is really hard to find. I think I'll just get a 10th gen NUC whenever they're released. Thanks for your advice though. I'm sure someone will eventually figure out how to get TB3 working w/ the T2 chip. I really like the general aesthetics and build quality of apple devices though. The more time + effort + struggle it takes to get Linux to run on a piece of hardware, the more I want to run Linux that piece of hardware ; ) To me, it represents the resilience of the open source community. That they figure out how to get s**t done with zero support from the vendor.
