### ISSUE TITLE
Installs well but wifi does not work (16,2 - BCM4364r4)

### ISSUE THREAD

**Issue by justinpchang** [mikeeq/mbp-fedora#40]
Hi all.

I followed the instructions in the README and got fedora installed. The next step would be to run update_kernel_mbp however I have no internet connection so the script fails. In settings, there are only options to set up wired connections, so I guess I'm missing drivers or something? My laptop and wifi adapter versions are listed in the title.

Thanks.

**Comment by justinpchang** [comment]
I tried to copy the firmware over using the instructions on the t2linux wiki but it says brcmfmac failed to initialize

**Comment by AdityaGarg8** [comment]
May I know the ISO you used.

**Comment by justinpchang** [comment]
@AdityaGarg8 the most recent release of this repo, Fedora 34 MBP15 26.08.2021

**Comment by AdityaGarg8** [comment]
@justinpchang use https://github.com/mikeeq/mbp-fedora/releases/tag/v5.13.12-f34-mbp16.

The MBP15 version is not compatible with 16,2. You need the MBP16 version

**Comment by justinpchang** [comment]
@AdityaGarg8 I'll try it today, thank you. Not sure how I missed the release name, just clicked on the most recent one!

**Comment by justinpchang** [comment]
@AdityaGarg8 I tried it with that release and it worked! Still had to apply the wifi fixes at the t2linux site, but works great now. Thanks so much for your help

**Comment by AdityaGarg8** [comment]
@justinpchang , if you are talking about iwd fixes then do them only if required. In some distros wpa2 is stable without iwd. Sometimes iwd behaves badly when it is not required.
