### ISSUE TITLE
Wireless not working

### ISSUE THREAD

**Issue by snibles** [mikeeq/mbp-fedora#43]
Hi!
Anyone had any luck with wireless networks?
I can only see wired connection when installing in a MacBook Pro 2019 15".
Anyone have any advice?

**Comment by AdityaGarg8** [comment]
What’s the output of uname -r

**Comment by AdityaGarg8** [comment]
And what’s your model indentifier. Follow https://wiki.t2linux.org/guides/wifi/ to check it.
