### ISSUE TITLE
kernel_Patch TouchBar error

### ISSUE THREAD

**Issue by kocierik** [mikeeq/mbp-fedora#45]
<i>make: Entering directory '/usr/src/kernels/5.14.9-200.mbp16.fc33.x86_64'
  CC [M]  /tmp/kernel_patch/touchbar/apple-ibridge.o
  CC [M]  /tmp/kernel_patch/touchbar/apple-ib-tb.o
  CC [M]  /tmp/kernel_patch/touchbar/apple-ib-als.o
/tmp/kernel_patch/touchbar/apple-ib-als.c: In function ‘appleals_config_iio’:
/tmp/kernel_patch/touchbar/apple-ib-als.c:490:50: error: ‘struct iio_dev’ has no member named ‘id’
  490 |                                           iio_dev->id);
      |                                                  ^~
make[1]: *** [scripts/Makefile.build:271: /tmp/kernel_patch/touchbar/apple-ib-als.o] Error 1
make: *** [Makefile:1858: /tmp/kernel_patch/touchbar] Error 2
make: Leaving directory '/usr/src/kernels/5.14.9-200.mbp16.fc33.x86_64'
</i>
<b>TouchBar doesn't work with this error. Is there a solution?</b>

**Comment by mikeeq** [comment]
Not sure why is it flagging an error, it's working locally on my machine and in the CI, so it needs to be specific to your environment.

**Comment by kocierik** [comment]
![issue](https://user-images.githubusercontent.com/41591336/140945120-8c52bbfa-b51e-4be8-b613-0cc21e42de42.png)
If I launch version 5.13.12 it works. (macOS Big Sur - version 11.6)
