### ISSUE TITLE
Any specific upgrade instruction from 34 to 35?

### ISSUE THREAD

**Issue by jinwk00** [mikeeq/mbp-fedora#47]
Since the mbp-fedora 35 was updated 11 days ago, and I have mbp-fedora 34 build, I would like to know if there are any specific instructions that I can follow. If not, then may I follow typical Fedora upgrade instructions?

**Comment by oboff** [comment]
https://github.com/mikeeq/mbp-fedora#how-to-upgrade-current-mbp-fedora-installations
