### ISSUE TITLE
Partition Problems

### ISSUE THREAD

**Issue by khanmo97** [mikeeq/mbp-fedora#49]
I'm not sure if this is a partition problem or the boot loader. Currently, the installation destination only has my entire SSD. It doesn't include the partition I made. My partition of the SSD is 200 GB in APFS format. I'm not sure where I went wrong. Here's a picture of what the installation destination looks like.

![image](https://user-images.githubusercontent.com/60152013/145722983-9c05778f-2b10-4fd5-a84c-1f987bd87795.jpeg)

I quit the installation because I'm scared about loosing macOS. I would really appreciate any help on this issue.

**Comment by ExperiBass** [comment]
Format the partition as FAT and then try installing, Linux doesn't recognize APFS.

**Comment by mikeeq** [comment]
It's documented in readme.md
