### ISSUE TITLE
Do you have a Patreon / Buymeacoffee / GH Sponsors?

### ISSUE THREAD

**Issue by nikodunk** [mikeeq/mbp-fedora#56]
Hi there,

This build provides a ton of value to me. I'd love to buy you at least a coffee or two. I cannot find another way to contact you to ask, but... do you have a GH Sponsor/ Patreon / Buymeacoffee account? 

After 6 months of successfully running your rebuild on my T2 Macbook Air and multiple Kernel upgrades, I'm very thankful for your work!

Best,
Niko

**Comment by Raphty** [comment]
Yes, I am just about to try this on my mac as well, and if it works I would like to give some money as well!!

**Comment by mikeeq** [comment]
GH sponsors were added, thanks guys for your support!
