### ISSUE TITLE
Having issues getting wifi working

### ISSUE THREAD

**Issue by BurrPro** [mikeeq/mbp-fedora#57]
Hey team, love the work you've put in - Fedora is running flawlessly on my 2018 MacBook Air 8,1

I've been trying to get wifi working for two days now, following the guides on t2linux - originally i had Catalina installed, and saw on a forum post that the Catalina drivers don't work.

I've now got Mojave installed - I'm not sure if these drivers are compatible with F35? Besides I tried and had no better results either. 

I downloaded the Big Sur firmware from 
https://github.com/AdityaGarg8/macOS-Big-Sur-WiFi-Firmware/tree/main/C-4355__s-C1
And tried again.  I manually moved the files into /tmp/apple-wifi-efi (compressed into wifi.tar.gz and also copied a folder containing the fw named wifi)

Unfortunately that didn't work either and I'm not sure what else to try without giving up or spending more hours over the next week trying to figure out what I'm doing wrong.

I ran `journalctl -k --grep=brcmfmac`, and here's the output:

```
$ journalctl -k --grep=brcmfmac
Apr 10 21:32:55 fedora kernel: usbcore: registered new interface driver brcmfmac
Apr 10 21:32:55 fedora kernel: brcmfmac 0000:02:00.0: enabling device (0000 -> 0002)
Apr 10 21:32:55 fedora kernel: brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4355-pcie for chip BCM4355/12
Apr 10 21:32:55 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355-pcie.bin failed with error -2
Apr 10 21:36:20 fedora kernel: usbcore: deregistering interface driver brcmfmac
Apr 10 21:36:20 fedora kernel: usbcore: registered new interface driver brcmfmac
Apr 10 21:36:20 fedora kernel: brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4355-pcie for chip BCM4355/12
Apr 10 21:36:20 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355-pcie.bin failed with error -2
```

Anything else I can try?

Thanks! Appreciate the work!

**Comment by AdityaGarg8** [comment]
It would be better if you upgrade your kernel using a wired internet (ethernet, USB tethering etc)

https://github.com/mikeeq/mbp-fedora-kernel#how-to-update-kernel-mbp

Then follow this guide

https://wiki.t2linux.org/guides/wifi/

**Comment by AdityaGarg8** [comment]
Basically, after upgrading the kernel only, the script would work.

**Comment by AdityaGarg8** [comment]
If you cannot upgrade, then you have to manually retrieve the firmware, manually rename it and paste it in Linux.

https://github.com/t2linux/wiki/blob/a4b46a7cfbe7efcbb6a0b6111e22172b0f5c4a77/docs/guides/wifi.md#retrieving-firmware

**Comment by AdityaGarg8** [comment]
> I downloaded the Big Sur firmware from https://github.com/AdityaGarg8/macOS-Big-Sur-WiFi-Firmware/tree/main/C-4355__s-C1 And tried again. I manually moved the files into /tmp/apple-wifi-efi (compressed into wifi.tar.gz and also copied a folder containing the fw named wifi)

Nope, this will rename the firmware wrongly. You basically attempted to use the script to dump Big Sur firmware into Linux, but that won't work because the renaming done by the script is different, and works in the upgraded kernel, not the one you have rn.

**Comment by BurrPro** [comment]
Thanks for such a quick response!! Was not expecting that at all

I will give that a shot, here's hoping updating the kernel works :+1: 

Thanks again, I'll update this thread with the results

**Comment by AdityaGarg8** [comment]
I forgot mention that it's recommended to upgrade macOS to the latest version before using the wifi script.

**Comment by BurrPro** [comment]
> I forgot mention that it's recommended to upgrade macOS to the latest version before using the wifi script.

I've been trying to avoid that as I'm only on ADSL and it takes about 4 hours to download macos...

I've reinstalled fedora to have a fresh start, and updated kernel + copied over firmware files correctly renamed for my chipset, although it's still not working.

When I run `sudo journalctl -k --grep=brcmfmac`

I'm getting this output:
```

Apr 11 00:14:50 fedora kernel: usbcore: registered new interface driver brcmfmac
Apr 11 00:14:50 fedora kernel: brcmfmac 0000:02:00.0: enabling device (0000 -> 0002)
Apr 11 00:14:50 fedora kernel: brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4355c1-pcie for chip BCM4355/12
Apr 11 00:14:50 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC-m-2.5-X3.bin failed with error -2
Apr 11 00:14:50 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC-m-2.5.bin failed with error -2
Apr 11 00:14:50 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC-m.bin failed with error -2
Apr 11 00:14:50 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC.bin failed with error -2
Apr 11 00:14:50 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-X3.bin failed with error -2
Apr 11 00:14:50 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii.bin failed with error -2
Apr 11 00:14:50 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.bin failed with error -2
Apr 11 00:16:48 fedora kernel: usbcore: deregistering interface driver brcmfmac
Apr 11 00:16:48 fedora kernel: usbcore: registered new interface driver brcmfmac
Apr 11 00:16:48 fedora kernel: brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4355c1-pcie for chip BCM4355/12
Apr 11 00:16:48 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC-m-2.5-X3.bin failed with error -2
Apr 11 00:16:48 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC-m-2.5.bin failed with error -2
Apr 11 00:16:48 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC-m.bin failed with error -2
Apr 11 00:16:48 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC.bin failed with error -2
Apr 11 00:16:48 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-X3.bin failed with error -2
Apr 11 00:16:48 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii.bin failed with error -2
Apr 11 00:16:48 fedora kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.bin failed with error -2

```

I'm going to give up for the night, but any suggestions on what i could try for tomorrow by any chance? :)

**Comment by AdityaGarg8** [comment]
Looks like you didn't use the script

**Comment by AdityaGarg8** [comment]
Now you simply have to use the script as mentioned in the wiki. Probably use firmware from Monterey.

**Comment by AdityaGarg8** [comment]
The renaming has to be done if you wanted to use the older kernel.

**Comment by AdityaGarg8** [comment]
So simply run the script macOS Monterey and then run it again in Fedora.

**Comment by BurrPro** [comment]
Solved it finally, wifi is working great!

Installed macOS Monterey, reinstalled fedora and updated the kernel - ran the script, after a reboot wifi worked perfectly.

Still having some quality of life issues such as sleep/ wake issues but I've seen some posts on how i can fix that around.

Thanks for the support and the great work team!
