### ISSUE TITLE
failed to download meta data 

### ISSUE THREAD

**Issue by CommieOrangePeel** [mikeeq/mbp-fedora#61]
[root@fedora ~]# FEDORA_VERSION=36 dnf system-upgrade download -y --releasever=${FEDORA_VERSION} --exclude='kernel*'
Fedora  - x86_64                                                34 kB/s |  93 kB     00:02    
Errors during downloading metadata for repository 'fedora':
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-&arch=x86_64 (IP: 152.19.134.198)
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-&arch=x86_64 (IP: 38.145.60.21)
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-&arch=x86_64 (IP: 38.145.60.20)
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-&arch=x86_64 (IP: 38.145.60.21)

**Comment by mikroskeem** [comment]
Try simply `dnf system-upgrade download -y --releasever=36 --exclude='kernel*'`
