### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by dmzoneill** [mikeeq/mbp-fedora#68]
Sorry i think i opened it on the wrong repo issues page.
On the README, that link to the wireless drivers is still broken.
I tried it in firefox and chrome and even with curl using **--no-certificate-check**.

Docs
Discord: https://discord.gg/Uw56rqW
WiFi firmware: https://packages.aunali1.com/apple/wifi-fw/18G2022
blog Installing Fedora 31 on a 2018 Mac mini: https://linuxwit.ch/blog/2020/01/installing-fedora-on-mac-mini/

![image](https://user-images.githubusercontent.com/15192260/203253142-d7f0cc57-0a76-4941-8410-8524552c97c7.png)

**Comment by dmzoneill** [comment]
```
dig packages.aunali1.com

; <<>> DiG 9.18.8-1-Debian <<>> packages.aunali1.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3715
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;packages.aunali1.com.		IN	A

;; ANSWER SECTION:
packages.aunali1.com.	300	IN	A	51.161.12.198

;; Query time: 47 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Tue Nov 22 07:38:51 GMT 2022
;; MSG SIZE  rcvd: 65

```

**Comment by mikeeq** [comment]
Fixed
