### ISSUE TITLE
failed to set new efi boot target. this is most likely a kernel bug

### ISSUE THREAD

**Issue by JohnQMetro** [mikeeq/mbp-fedora#7]
I got this error message when Fedora was installing the bootloader (using latest version). This is to an external usb hard drive. I continued, hoping the post install script mentioned in 'Known Issues' would fix this, but no luck. The EFI partition was also still HFS, and trying the reformat it to FAT32 using diskutil bugged out (the disk will have to be re-initialized).

**Comment by zhewang95** [comment]
I also encountered this error message during installation. Just ignore it and I can boot into system through rEFInd.

**Comment by JohnQMetro** [comment]
I think the real problem is the EFI partition still being HFS+, when 'HFS+ ESP is reformatted to FAT32 in post-scripts step' is supposed to happen. I don't like messing with OS X boot, so I avoided rEFInd and for my second try used command line utilities (after the installer was done) to backup the HFS+ESP, reformat it to FAT32, and copy the EFI files back.

Of course, installing the wifi firmware files then prevented the installation from booting completely.

Annoyingly, I also found that the Mac would not boot macOS from (a separate partition on) that disk unless the EFI parition was _named_ EFI, despite macOS not using the EFI, and an older Mac not having any problems.

**Comment by JohnQMetro** [comment]
I've gotten around the wifi issues, so I'd like to thank mikeeq for providing this iso!

**Comment by geovie** [comment]
I had the same error and solved it by executing the post-install script manually.
I think the problem is that the post install script is checking `/etc/fstab` of the live system:
https://github.com/mikeeq/mbp-fedora/blob/90031216462f09728fb9497e52fc9cb0f732a6e9/files/post-install-kickstart/97-mbp-post-install.ks#L6
should probably be 
```bash
if cat ${ANA_INSTALL_PATH}/etc/fstab | grep hfsplus ; then
```


@JohnQMetro How did you solved your wifi issues?

**Comment by mikeeq** [comment]
@geovie You're correct. I will fix that in incoming release with 5.4.7 kernel (upstream NVMe patch).

**Comment by JohnQMetro** [comment]
@geovie : It was pretty simple: I did not name the txt file correctly. As soon as I renamed it to _exactly the same_ as the instructions, and then restarted the NetworkManager service, the wifi started working.

**Comment by ktb92677** [comment]
@JohnQMetro hey, is there any chance you could take a look at the issue I posted to see if I have everything correct for file names for the wifi driver files? https://github.com/mikeeq/mbp-fedora/issues/8
