### ISSUE TITLE
Failing to see bluetooth 

### ISSUE THREAD

**Issue by joshji** [mikeeq/mbp-fedora#73]
my system cannot seem to see my macs bluetooth card. Is bluetooth capability yet to be implemented or is there some sort of fault with my configuration?

**Comment by Redecorating** [comment]
Hi, It should be possible to get bluetooth working. A few questions to help us figure out what's going on:

Can you run each of these commands in your terminal in linux, and send the output of each here?
    - `cat /sys/devices/virtual/dmi/id/product_name`
    - `uname -r`
    - `journalctl -k | grep -e hci0 -e lpss -e uart -e 4377`
    - `rfkill`
    - `systemctl status bluetooth`

**Comment by mikeeq** [comment]
You need to update your Fedora installation, especially kernel to get bluetooth working.
