### ISSUE TITLE
Fedora Silverblue/Kinoite support

### ISSUE THREAD

**Issue by big-harry** [mikeeq/mbp-fedora#75]
Will there be any plans to create images for OSTree based Fedora versions?

**Comment by sharpenedblade** [comment]
> Will there be any plans to create images for OSTree based Fedora versions?

You can install this kernel onto a normal silverblue install with `rpm-ostree`

**Comment by big-harry** [comment]
I guess that works then, I was just curious if there would be a dedicated image created automatically.
